maintainer "Amazon Web Services"
description "Deploy applications"
version "0.1"
recipe "custom_deploy::scm", "Install and setup the source code management system"
recipe "custom_deploy::rails", "Deploy a Rails application"
recipe "custom_deploy::rails-undeploy", "Remove a Rails application"
recipe "custom_deploy::mysql", "Create the MySQL database for an app"
recipe "custom_deploy::mysql-configure", "Reconfigure the database"
recipe "custom_deploy::logrotate", "Logrotate configuration for log files in shared/log/"

depends "dependencies"
depends "nginx"
depends "ssh_users"
depends "opsworks_agent_monit"
